spring:
  profiles:
    active: windows
  application:
    # springcloud会用到服务名
    name: api-edu

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #必须设置，否则jackson返回的日期统统晚了8小时
    time-zone: GMT+8

server:
  port: 8001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    root: info
#  file:
#    name: /User/liukaiyu/Desktop/edu.log


---
spring:
  profiles: windows
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elliot_education?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      connection-test-query: select 1
      connection-timeout: 60000
      maximum-pool-size: 12
      idle-timeout: 500000
      max-lifetime: 540000
      minimum-idle: 10
      pool-name: Elliot-pool

---
spring:
  profiles: macOs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elliot_education?serverTimezone=GMT%2B8
    username: root
    password: 12345678
    hikari:
      connection-test-query: select 1
      connection-timeout: 60000
      maximum-pool-size: 12
      idle-timeout: 500000
      max-lifetime: 540000
      minimum-idle: 10
      pool-name: Elliot-pool


